# Generated by Django 4.1.13 on 2026-05-08 06:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Semantic event name, e.g. work_order.created",
                        max_length=255,
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        help_text="Domain entity type, e.g. work_order", max_length=100
                    ),
                ),
                (
                    "aggregate_id",
                    models.UUIDField(help_text="ID of the related aggregate/entity"),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Self-contained immutable event payload"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "event_version",
                    models.PositiveIntegerField(
                        default=1, help_text="Schema/event contract version"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Optional deduplication key for consumers. Unique per tenant when provided.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source_service",
                    models.CharField(
                        blank=True,
                        help_text="Origin service or bounded context",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=False,
                        help_text="Tenant owner of this event",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "outbox_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["tenant_id", "status", "created_at"],
                name="idx_outbox_status_created",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["tenant_id", "aggregate_type", "aggregate_id"],
                name="idx_outbox_tenant_aggregate",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["tenant_id", "event_type"], name="idx_outbox_tenant_event_type"
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["tenant_id", "idempotency_key"],
                name="idx_outbox_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("tenant_id", "idempotency_key"),
                name="uq_outbox_tenant_idempotency_key",
            ),
        ),
    ]
