# Generated by Django 4.1.13 on 2026-05-07 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Semantic event name, e.g. work_order.created",
                        max_length=255,
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        db_index=True,
                        help_text="Domain entity type, e.g. work_order",
                        max_length=100,
                    ),
                ),
                (
                    "aggregate_id",
                    models.UUIDField(
                        db_index=True, help_text="ID of the related aggregate/entity"
                    ),
                ),
                ("payload", models.JSONField(help_text="Self-contained event payload")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("event_version", models.PositiveIntegerField(default=1)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "outbox_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["status", "created_at"], name="idx_outbox_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["aggregate_type", "aggregate_id"], name="idx_outbox_aggregate"
            ),
        ),
    ]
