# Generated by Django 4.1.13 on 2026-05-10 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("work_order", "0001_initial"),
        ("work_order_type", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="work_order_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="work_order_type.workordertype",
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["tenant", "deleted_at"], name="idx_work_order_tenant_deleted"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["tenant", "status"], name="idx_work_order_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["tenant", "asset"], name="idx_work_order_tenant_asset"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["tenant", "assigned_to"], name="idx_work_order_tenant_assigned"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["tenant", "due_date"], name="idx_work_order_tenant_due_date"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["tenant", "priority"], name="idx_work_order_tenant_priority"
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("completed_date__isnull", True),
                    ("status", "completed"),
                    _connector="OR",
                ),
                name="chk_work_order_completed_date_requires_completed_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("due_date__isnull", True),
                    ("scheduled_date__isnull", True),
                    ("due_date__gte", models.F("scheduled_date")),
                    _connector="OR",
                ),
                name="chk_work_order_due_date_after_scheduled",
            ),
        ),
    ]
