# Generated by Django 4.1.13 on 2026-05-08 06:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
        ("asset_type", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Manufacturer serial number (unique per tenant)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("location", models.CharField(db_index=True, max_length=255)),
                ("installation_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                (
                    "recommended_maintenance_interval_days",
                    models.PositiveIntegerField(),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="asset_type.assettype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "assets",
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["tenant", "deleted_at"], name="idx_asset_tenant_deleted"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["tenant", "status"], name="idx_asset_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["tenant", "asset_type"], name="idx_asset_tenant_type"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["tenant", "last_maintenance_date"],
                name="idx_asset_tenant_maintenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                check=models.Q(("recommended_maintenance_interval_days__gt", 0)),
                name="chk_recommended_interval_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("last_maintenance_date__isnull", True),
                    ("last_maintenance_date__gte", models.F("installation_date")),
                    _connector="OR",
                ),
                name="chk_last_maintenance_after_installation",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("serial_number__isnull", False)
                ),
                fields=("tenant", "serial_number"),
                name="uq_tenant_active_serial_number",
            ),
        ),
    ]
