# Generated by Django 4.1.13 on 2026-05-09 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="User responsible for supervising this asset",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["tenant", "supervisor"],
                name="idx_asset_tenant_supervisor",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["supervisor", "status"],
                name="idx_asset_supervisor_status",
            ),
        ),
    ]
