# Generated by Django 4.1.13 on 2026-05-09 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def check_no_null_supervisors(apps, schema_editor):
    Asset = apps.get_model("asset", "Asset")
    count = Asset.objects.filter(supervisor__isnull=True).count()
    if count:
        raise Exception(
            f"Cannot migrate: {count} asset(s) have no supervisor assigned. "
            "Assign a supervisor to every asset before running this migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("asset", "0002_asset_supervisor_asset_idx_asset_tenant_supervisor_and_more"),
    ]

    operations = [
        migrations.RunPython(
            check_no_null_supervisors,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="asset",
            name="supervisor",
            field=models.ForeignKey(
                help_text="User responsible for supervising this asset",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supervised_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
