# Generated by Django 4.1.13 on 2026-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0003_supervisor_required"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="asset",
            name="uq_tenant_active_serial_number",
        ),
        migrations.AlterField(
            model_name="asset",
            name="serial_number",
            field=models.CharField(
                db_index=True,
                default=1,
                help_text="Manufacturer serial number (unique per tenant)",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant", "serial_number"),
                name="uq_tenant_active_serial_number",
            ),
        ),
    ]
