# Generated by Django 4.1.13 on 2026-05-10 04:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human readable work order type name",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order_types",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "work_order_types",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="workordertype",
            index=models.Index(
                fields=["tenant", "name"], name="idx_wo_type_tenant_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="workordertype",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_wo_type_tenant_name"
            ),
        ),
    ]
